import { generatePageMetadata } from "@/lib/metadata";
import type { Metadata } from "next";
import { MarketingPageShell } from "@/components/layout/MarketingPageShell";
import { MKT } from "@/lib/marketing-ui";

export const metadata: Metadata = generatePageMetadata({
  title: 'Privacy Policy',
  description: 'Read how NomoExam collects, uses, and protects your personal data. Learn about your privacy rights and how we keep your information secure.',
  path: '/privacy-policy',
  keywords: ['privacy policy', 'data protection', 'personal data', 'privacy rights', 'GDPR', 'data security', 'user privacy', 'information collection'],
});

export default function PrivacyPolicyPage() {
  return (
    <MarketingPageShell>
      <main className={`${MKT.container} pt-24 md:pt-28 py-12 md:py-16`}>
        <article className="prose prose-neutral max-w-4xl mx-auto font-barlow prose-headings:font-heading prose-headings:italic prose-headings:text-neutral-900 prose-p:text-neutral-600 prose-p:font-medium prose-a:font-semibold prose-a:text-neutral-900 prose-a:underline prose-a:decoration-accent-lime/70 prose-a:underline-offset-4 lg:prose-lg">
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
          <h2>Definitions</h2>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
            </li>
            <li>
              <p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to nomoexam.</p>
            </li>
            <li>
              <p><strong>Country</strong> refers to: Virginia,  United States</p>
            </li>
            <li>
              <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
            </li>
            <li>
              <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
            </li>
            <li>
              <p><strong>Service</strong> refers to the Website.</p>
            </li>
            <li>
              <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            </li>
            <li>
              <p><strong>Website</strong> refers to nomoexam, accessible from <a href="https://www.nomoexam.com" rel="external nofollow noopener" target="_blank">https://www.nomoexam.com</a></p>
            </li>
            <li>
              <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
            </li>
          </ul>
          <h2>Collecting and Using Your Personal Data</h2>
          <h3>Types of Data Collected</h3>
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul>
            <li><p>Email address</p></li>
            <li><p>First name and last name</p></li>
            <li><p>Account information (Firebase UID)</p></li>
            <li><p>Exam scores and practice attempts</p></li>
            <li><p>Progress tracking data</p></li>
            <li><p>Payment information (processed by Stripe, not stored by us)</p></li>
            <li><p>Device information and analytics data</p></li>
            <li><p>Usage Data</p></li>
          </ul>
          <h3>Third-Party Services</h3>
          <p>We use the following third-party services to provide and improve our Service:</p>
          <ul>
            <li><p><strong>Firebase (Google):</strong> Authentication, database, and hosting services</p></li>
            <li><p><strong>Stripe:</strong> Payment processing (does not share your payment details with us)</p></li>
            <li><p><strong>Vercel:</strong> Website hosting and content delivery</p></li>
            <li><p><strong>Google Analytics:</strong> Usage analytics and service improvement</p></li>
          </ul>
          <p>These services may collect and process your data according to their own privacy policies.</p>
          <h3>Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li>
              <p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
            </li>
            <li>
              <p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
            </li>
            <li>
              <p><strong>To contact You:</strong> To contact You by email regarding updates or informative communications related to the functionalities, products or contracted services.</p>
            </li>
            <li>
              <p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
            </li>
          </ul>
          <h3>Retention of Your Personal Data</h3>
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
          <h3>Disclosure of Your Personal Data</h3>
          <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>
          <h3>Security of Your Personal Data</h3>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          <h2>Your Rights</h2>
          <p>You have the following rights regarding your personal data:</p>
          <ul>
            <li><p><strong>Access:</strong> Request a copy of your personal data</p></li>
            <li><p><strong>Correction:</strong> Update or correct inaccurate data</p></li>
            <li><p><strong>Deletion:</strong> Request deletion of your account and data</p></li>
            <li><p><strong>Export:</strong> Request a copy of your data in portable format</p></li>
            <li><p><strong>Opt-out:</strong> Disable analytics and marketing communications</p></li>
          </ul>
          <h3>Data Deletion</h3>
          <p>To delete your account and all associated data, please email us at <a href="mailto:support@nomoexam.com?subject=Delete My Account">support@nomoexam.com</a> with the subject "Delete My Account". We will process your request within 48 hours.</p>
          <p>Upon account deletion, the following data will be permanently removed:</p>
          <ul>
            <li>Your profile and account information</li>
            <li>All exam attempts and scores</li>
            <li>Progress tracking data</li>
            <li>Subscription information (active subscriptions will be cancelled)</li>
          </ul>
          <h2>Data Security</h2>
          <p>We implement industry-standard security measures including:</p>
          <ul>
            <li>HTTPS encryption for all data transmission</li>
            <li>Secure authentication via Firebase</li>
            <li>Regular security updates and monitoring</li>
            <li>Limited employee access to personal data</li>
          </ul>
          <h2>Children's Privacy</h2>
          <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
          <h2>Changes to this Privacy Policy</h2>
          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. Changes are effective immediately upon posting.</p>
          <p><strong>Last Updated:</strong> March 10, 2026</p>
          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy or wish to exercise your rights, You can contact us:</p>
          <ul>
            <li>By email: <a href="mailto:support@nomoexam.com">support@nomoexam.com</a></li>
            <li>Response time: Within 48 hours</li>
          </ul>
        </article>
      </main>
    </MarketingPageShell>
  );
}